// Generates the database seed and the pricing parity tests from the Dart
// code, so the backend can never drift from the app:
//
//   * supabase/seed/10_catalog.generated.sql — sellers, products, variants,
//     categories, banners and try-on model photos from the mock catalogue;
//   * supabase/tests/database/90_pricing_parity.generated.test.sql — pgTAP
//     checks that the SQL money maths gives the same answers as Dart.
//
// The files are golden files: this test fails when they are out of date.
// Regenerate with:
//   flutter test --update-goldens test/tool/backend_fixtures_test.dart
import 'dart:io';
import 'package:clothsy_core/core/utils/money_split.dart';
import 'package:clothsy_core/features/cart/domain/entities/cart_item.dart';
import 'package:clothsy_core/features/cart/domain/entities/coupon.dart';
import 'package:clothsy_core/features/orders/domain/order_splitter.dart';
import 'package:clothsy_shop/features/catalog/data/repositories/mock_catalog_repository.dart';
import 'package:clothsy_shop/features/tryon/data/repositories/mock_tryon_repository.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _sizeOrder = ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'One Size'];

String _q(String? value) =>
    value == null ? 'null' : "'${value.replaceAll("'", "''")}'";

String _textArray(Iterable<String> values) => values.isEmpty
    ? "'{}'::text[]"
    : 'array[${values.map(_q).join(', ')}]::text[]';

String _uuid(String kind, String id) => "md5('clothsy:$kind:$id')::uuid";

/// Mock colours are written "0xFFRRGGBB"; the database keeps "#RRGGBB".
String _hex(String value) {
  final digits = value.replaceFirst(RegExp(r'^(0x|#)'), '');
  return '#${digits.length == 8 ? digits.substring(2) : digits}'.toUpperCase();
}

Future<String> _catalogSql() async {
  final repo = MockCatalogRepository();
  final sellers = await repo.getSellers();
  final products = await repo.getProducts(limit: 1000);
  final categories = await repo.getCategories();
  final banners = await repo.getFeaturedBanners();

  // Category membership exactly as the app filters it.
  final memberships = <String, List<String>>{};
  for (final category in categories) {
    if (category.handle == 'all') continue;
    for (final p in await repo.getProducts(
      category: category.title,
      limit: 1000,
    )) {
      memberships.putIfAbsent(p.id, () => []).add(category.handle);
    }
  }

  final b = StringBuffer()
    ..writeln(
      '-- GENERATED by apps/customer/test/tool/backend_fixtures_test.dart',
    )
    ..writeln('-- from the mock catalogue. Do not edit by hand.')
    ..writeln("select set_config('clothsy.stock_reason', 'seed', true);")
    ..writeln();

  b.writeln(
    'insert into public.sellers (id, handle, name, tagline, story, logo_url,',
  );
  b.writeln(
    '  banner_url, city, status, is_verified, is_independent, follower_count,',
  );
  b.writeln('  rating, dispatch_days, return_window_days) values');
  b.writeln(
    [
      for (final s in sellers)
        "  (${_uuid('seller', s.id)}, ${_q(s.handle)}, ${_q(s.name)}, ${_q(s.tagline)}, "
            '${_q(s.story)}, ${_q(s.logoUrl)}, ${_q(s.bannerUrl)}, ${_q(s.city)}, '
            "'approved', ${s.isVerified}, ${s.isIndependent}, ${s.followerCount}, "
            '${s.rating}, ${s.dispatchDays}, ${s.returnWindowDays})',
    ].join(',\n'),
  );
  b.writeln(';\n');

  b.writeln(
    'insert into public.categories (id, handle, title, icon_name, sort_order) values',
  );
  b.writeln(
    [
      for (final (i, c) in categories.indexed)
        // Icons are chosen by the app from the handle.
        "  (${_uuid('category', c.id)}, ${_q(c.handle)}, ${_q(c.title)}, "
            'null, $i)',
    ].join(',\n'),
  );
  b.writeln(';\n');

  b.writeln(
    'insert into public.banners (id, headline, subtitle, cta_text, image_url,',
  );
  b.writeln('  deep_link, sort_order) values');
  b.writeln(
    [
      for (final (i, banner) in banners.indexed)
        "  (${_uuid('banner', banner.id)}, ${_q(banner.headline)}, ${_q(banner.subtitle)}, "
            '${_q(banner.ctaText)}, ${_q(banner.imageUrl)}, '
            '${_q(banner.deepLinkTarget)}, $i)',
    ].join(',\n'),
  );
  b.writeln(';\n');

  b.writeln(
    'insert into public.products (id, seller_id, handle, title, description,',
  );
  b.writeln(
    '  category, category_handles, tags, images, rating, review_count,',
  );
  b.writeln(
    '  is_tryon_eligible, is_featured, is_new, status, sort_rank) values',
  );
  b.writeln(
    [
      for (final (i, p) in products.indexed)
        "  (${_uuid('product', p.id)}, ${_uuid('seller', p.sellerId)}, ${_q(p.handle)}, "
            '${_q(p.title)}, ${_q(p.description)}, ${_q(p.category)}, '
            '${_textArray(memberships[p.id] ?? const [])}, ${_textArray(p.tags)}, '
            '${_textArray(p.images)}, ${p.rating}, ${p.reviewCount}, '
            "${p.isTryonEligible}, ${p.isFeatured}, ${p.isNew}, 'live', $i)",
    ].join(',\n'),
  );
  b.writeln(';\n');

  b.writeln(
    'insert into public.product_variants (id, product_id, seller_id, sku, title,',
  );
  b.writeln(
    '  size, size_rank, color_name, color_hex, price, compare_at_price, stock,',
  );
  b.writeln('  image_url, position) values');
  b.writeln(
    [
      for (final p in products)
        for (final (i, v) in p.variants.indexed)
          "  (${_uuid('variant', v.id)}, ${_uuid('product', p.id)}, "
              "${_uuid('seller', p.sellerId)}, ${_q(v.id)}, ${_q(v.title)}, ${_q(v.size)}, "
              '${_sizeOrder.contains(v.size) ? _sizeOrder.indexOf(v.size) : 100}, '
              '${_q(v.colorName)}, ${_q(_hex(v.colorHex))}, ${v.price}, '
              '${v.originalPrice != null && v.originalPrice! > v.price ? v.originalPrice : 'null'}, '
              '${v.inventoryQuantity}, ${_q(v.imageUrl)}, $i)',
    ].join(',\n'),
  );
  b.writeln(';\n');

  final presets = await MockTryOnRepository().getPresetPhotos();
  b.writeln(
    'insert into public.tryon_presets (id, slug, label, image_url, sort_order) values',
  );
  b.writeln(
    [
      for (final (i, preset) in presets.indexed)
        "  (${_uuid('preset', preset.id)}, ${_q(preset.id)}, ${_q(preset.label)}, "
            '${_q(preset.imageUrl)}, $i)',
    ].join(',\n'),
  );
  b.writeln(';');
  return b.toString();
}

String _parityTestSql() {
  final splitCases = <(int, List<int>)>[
    (1000, [1, 1, 1]),
    (10, [1, 1, 1]),
    (50000, [799900, 499900]),
    (100, [3, 3, 3, 1]),
    (99999, [3, 7, 11, 13]),
    (7, [1000000, 1, 1]),
    (-1000, [1, 1, 1]),
    (0, [5, 5]),
    (500, [0, 0]),
  ];
  final shippingCases = [0, 1, 99900, 199899, 199900, 500000];
  final coupons = <(String, CouponRule, int)>[
    ('10% of 12998', const CouponRule(code: 'T', percentBps: 1000), 1299800),
    ('10% rounds half up', const CouponRule(code: 'T', percentBps: 1000), 5),
    ('20% of 4999', const CouponRule(code: 'T', percentBps: 2000), 499900),
    (
      'capped percent',
      const CouponRule(code: 'T', percentBps: 5000, maxDiscount: 50000),
      300000,
    ),
    ('flat above goods', const CouponRule(code: 'T', flatAmount: 50000), 30000),
    (
      'min not met',
      const CouponRule(code: 'T', percentBps: 1000, minSubtotal: 99900),
      99800,
    ),
  ];

  final tests = <String>[];
  for (final (amount, weights) in splitCases) {
    tests.add(
      'select is(private.split_proportionally($amount, array[${weights.join(', ')}]::bigint[]), '
      "array[${splitProportionally(amount, weights).join(', ')}]::integer[], "
      "'split $amount over $weights');",
    );
  }
  for (final subtotal in shippingCases) {
    final fee = CartSummary.shippingFeeFor(subtotal);
    tests.add(
      "select is(private.shipping_fee($subtotal), $fee, 'shipping on $subtotal');",
    );
  }
  for (final (label, rule, goods) in coupons) {
    final type = rule.percentBps != null ? 'percent' : 'flat';
    tests.add(
      'select is(private.coupon_discount(row('
      "gen_random_uuid(), 'T', '$type', ${rule.percentBps ?? 'null'}, "
      "${rule.flatAmount ?? 'null'}, ${rule.maxDiscount ?? 'null'}, ${rule.minSubtotal}, "
      "null, null, null, null, false, true, 'platform', now())::public.coupons, $goods), "
      "${rule.discountFor(goods)}, 'coupon: $label');",
    );
  }
  for (final i in [0, 1, 25, 26]) {
    tests.add(
      "select is(private.seller_suffix($i), '${OrderSplitter.suffix(i)}', 'suffix $i');",
    );
  }

  return [
    '-- GENERATED by apps/customer/test/tool/backend_fixtures_test.dart: the',
    '-- Dart money maths is the specification, these check the SQL agrees.',
    'begin;',
    'create extension if not exists pgtap with schema extensions;',
    'set search_path = public, extensions;',
    'select plan(${tests.length});',
    ...tests,
    'select * from finish();',
    'rollback;',
    '',
  ].join('\n');
}

Future<void> _expectFile(String relativePath, String content) async {
  // Tests run from apps/customer.
  final file = File('../../$relativePath');
  if (autoUpdateGoldenFiles || !file.existsSync()) {
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(content);
    return;
  }
  expect(
    file.readAsStringSync(),
    content,
    reason:
        '$relativePath is out of date. Run: flutter test --update-goldens '
        'test/tool/backend_fixtures_test.dart',
  );
}

void main() {
  setUp(() => SharedPreferences.setMockInitialValues({}));

  test('catalogue seed matches the mock catalogue', () async {
    await _expectFile(
      'supabase/seed/10_catalog.generated.sql',
      await _catalogSql(),
    );
  });

  test('pricing parity tests match the Dart money maths', () async {
    await _expectFile(
      'supabase/tests/database/90_pricing_parity.generated.test.sql',
      _parityTestSql(),
    );
  });
}
