-- GENERATED by apps/customer/test/tool/backend_fixtures_test.dart
-- from the mock catalogue. Do not edit by hand.
select set_config('clothsy.stock_reason', 'seed', true);

insert into public.sellers (id, handle, name, tagline, story, logo_url,
  banner_url, city, status, is_verified, is_independent, follower_count,
  rating, dispatch_days, return_window_days) values
  (md5('clothsy:seller:sel_noor')::uuid, 'noor-atelier', 'Noor Atelier', 'Hand-finished occasion & workwear', 'Noor Atelier started in a Jaipur studio with two tailors and a love for hand-block prints. Every piece is cut in small batches, finished by hand and made to be worn again and again.', null, 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=1200&auto=format&fit=crop&q=80', 'Jaipur', 'approved', true, true, 48200, 4.8, 2, 10),
  (md5('clothsy:seller:sel_rao')::uuid, 'studio-rao', 'Studio Rao', 'Sharp, modern tailoring for him', 'Studio Rao makes the shirt, blazer and trouser you reach for every week. Clean lines, breathable fabrics and a fit that works from office to dinner.', null, 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=1200&auto=format&fit=crop&q=80', 'Mumbai', 'approved', true, true, 31400, 4.7, 3, 7),
  (md5('clothsy:seller:sel_lilac')::uuid, 'the-lilac-edit', 'The Lilac Edit', 'Soft colour, easy silhouettes', 'A small Bengaluru label for people who like their wardrobe calm: soft colours, relaxed shapes and fabrics that feel good all day.', null, 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=1200&auto=format&fit=crop&q=80', 'Bengaluru', 'approved', true, true, 12900, 4.6, 2, 7),
  (md5('clothsy:seller:sel_mehr')::uuid, 'mehr-essentials', 'Mehr Essentials', 'Everyday basics in honest fabrics', 'Mehr Essentials is new to Clothsy: simple, well-made everyday pieces at fair prices.', null, 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=1200&auto=format&fit=crop&q=80', 'New Delhi', 'approved', false, true, 2300, 4.4, 4, 7)
;

insert into public.categories (id, handle, title, icon_name, sort_order) values
  (md5('clothsy:category:col_all')::uuid, 'all', 'All', null, 0),
  (md5('clothsy:category:col_men')::uuid, 'men', 'Men', null, 1),
  (md5('clothsy:category:col_women')::uuid, 'women', 'Women', null, 2),
  (md5('clothsy:category:col_dresses')::uuid, 'dresses', 'Dresses', null, 3),
  (md5('clothsy:category:col_tops')::uuid, 'tops', 'Tops', null, 4),
  (md5('clothsy:category:col_outerwear')::uuid, 'outerwear', 'Outerwear', null, 5),
  (md5('clothsy:category:col_shoes')::uuid, 'shoes', 'Shoes', null, 6),
  (md5('clothsy:category:col_bags')::uuid, 'bags', 'Bags', null, 7)
;

insert into public.banners (id, headline, subtitle, cta_text, image_url,
  deep_link, sort_order) values
  (md5('clothsy:banner:b1')::uuid, 'New Season
New Styles', 'Up to 40% off on latest collection', 'Shop Now', 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80', '/explore', 0),
  (md5('clothsy:banner:b2')::uuid, 'See it
on you.', 'Experience photorealistic AI Virtual Try-On', 'Try It On', 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&auto=format&fit=crop&q=80', '/tryon', 1),
  (md5('clothsy:banner:b3')::uuid, 'Exclusive Silk
Collection', 'Up to 40% off on signature pieces', 'Shop Silk', 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80', '/explore', 2)
;

insert into public.products (id, seller_id, handle, title, description,
  category, category_handles, tags, images, rating, review_count,
  is_tryon_eligible, is_featured, is_new, status, sort_rank) values
  (md5('clothsy:product:p_lavender_blazer')::uuid, md5('clothsy:seller:sel_noor')::uuid, 'lavender-blazer', 'Lavender Blazer', 'Tailored to perfection, this blazer adds a touch of elegance to any outfit. Crafted from premium breathable stretch twill with structured notch lapels, flap pockets, and a graceful tailored silhouette. Perfect for both casual and formal occasions.', 'Women', array['women', 'outerwear']::text[], array['Blazer', 'Outerwear', 'Women', 'Lavender', 'Featured']::text[], array['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=900&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=900&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900&auto=format&fit=crop&q=80']::text[], 4.8, 120, true, true, true, 'live', 0),
  (md5('clothsy:product:p_minimal_overshirt')::uuid, md5('clothsy:seller:sel_rao')::uuid, 'minimal-overshirt', 'Minimal Overshirt', 'Clean-cut contemporary overshirt made with premium structured cotton twill. Features natural horn buttons, tailored collar, and clean dual utility chest pockets.', 'Men', array['men']::text[], array['Shirt', 'Overshirt', 'Men', 'Featured']::text[], array['https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=900&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=900&auto=format&fit=crop&q=80']::text[], 4.9, 88, true, true, true, 'live', 1),
  (md5('clothsy:product:p_lavender_hoodie')::uuid, md5('clothsy:seller:sel_lilac')::uuid, 'lavender-hoodie', 'Lavender Hoodie', 'Ultra-soft heavyweight brushed organic cotton fleece hoodie with relaxed dropped shoulders, double-layered hood, and ribbed trims.', 'Women', array['women']::text[], array['Hoodie', 'Sweater', 'Women', 'Lavender', 'Featured']::text[], array['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=900&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=900&auto=format&fit=crop&q=80']::text[], 4.7, 145, true, true, true, 'live', 2),
  (md5('clothsy:product:p1')::uuid, md5('clothsy:seller:sel_noor')::uuid, 'silk-satin-maxi-dress', 'Silk Satin Maxi Dress', 'Cut on the bias for an effortless, figure-skimming drape. Crafted from premium 22-momme Mulberry silk satin with adjustable delicate straps and a subtle cowl neckline. Perfect for evenings and celebrations.', 'Dresses', array['women', 'dresses']::text[], array['Silk', 'Evening', 'Maxi', 'Dresses']::text[], array['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=900&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=900&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=900&auto=format&fit=crop&q=80']::text[], 4.9, 184, true, true, true, 'live', 3),
  (md5('clothsy:product:p2')::uuid, md5('clothsy:seller:sel_rao')::uuid, 'linen-tailored-blazer', 'Linen Tailored Blazer', 'Structured yet lightweight, crafted from pure Normandy flax linen. Features structured lapels, tortoiseshell buttons, and a relaxed tailored fit that pairs effortlessly with tailored trousers or slip skirts.', 'Outerwear', array['women', 'outerwear']::text[], array['Linen', 'Blazer', 'Tailored', 'Outerwear']::text[], array['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=900&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&auto=format&fit=crop&q=80']::text[], 4.8, 96, true, true, true, 'live', 4),
  (md5('clothsy:product:p3')::uuid, md5('clothsy:seller:sel_lilac')::uuid, 'pleated-slip-midi-gown', 'Pleated Slip Midi Gown', 'Delicate micro-accordion pleats enhance every movement. Finished with a subtle asymmetric hemline and graceful silhouette.', 'Dresses', array['women', 'dresses']::text[], array['Pleated', 'Midi', 'Dresses']::text[], array['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=900&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=900&auto=format&fit=crop&q=80']::text[], 4.7, 65, true, true, false, 'live', 5),
  (md5('clothsy:product:p4')::uuid, md5('clothsy:seller:sel_mehr')::uuid, 'cashmere-blend-knit-top', 'Cashmere Blend Knit Top', 'Supremely soft Mongolian cashmere spun with organic cotton. A timeless mock-neck silhouette designed for transitional season layering.', 'Tops', array['tops']::text[], array['Knitwear', 'Cashmere', 'Tops']::text[], array['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=900&auto=format&fit=crop&q=80']::text[], 4.9, 112, true, false, true, 'live', 6),
  (md5('clothsy:product:p5')::uuid, md5('clothsy:seller:sel_noor')::uuid, 'sculpted-leather-tote', 'Sculpted Leather Tote', 'Full-grain Italian calfskin leather handcrafted with architectural curved handles and gold-tone custom hardware.', 'Bags', array['bags']::text[], array['Leather', 'Bags', 'Accessories']::text[], array['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900&auto=format&fit=crop&q=80']::text[], 4.9, 78, false, true, false, 'live', 7),
  (md5('clothsy:product:p6')::uuid, md5('clothsy:seller:sel_rao')::uuid, 'minimalist-ankle-strap-heels', 'Minimalist Ankle Strap Heels', '75mm sculptural stiletto heel with delicate ankle strap and cushioned memory foam insole for all-evening comfort.', 'Shoes', array['shoes']::text[], array['Shoes', 'Heels', 'Footwear']::text[], array['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&auto=format&fit=crop&q=80']::text[], 4.8, 53, false, false, true, 'live', 8)
;

insert into public.product_variants (id, product_id, seller_id, sku, title,
  size, size_rank, color_name, color_hex, price, compare_at_price, stock,
  image_url, position) values
  (md5('clothsy:variant:v_blazer_lavender')::uuid, md5('clothsy:product:p_lavender_blazer')::uuid, md5('clothsy:seller:sel_noor')::uuid, 'v_blazer_lavender', 'Soft Lavender / M', 'M', 3, 'Soft Lavender', '#B9A6E0', 799900, 999900, 10, 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&auto=format&fit=crop&q=80', 0),
  (md5('clothsy:variant:v_blazer_champagne')::uuid, md5('clothsy:product:p_lavender_blazer')::uuid, md5('clothsy:seller:sel_noor')::uuid, 'v_blazer_champagne', 'Warm Sand / S', 'S', 2, 'Warm Sand', '#E7DCC7', 799900, 999900, 10, null, 1),
  (md5('clothsy:variant:v_blazer_charcoal')::uuid, md5('clothsy:product:p_lavender_blazer')::uuid, md5('clothsy:seller:sel_noor')::uuid, 'v_blazer_charcoal', 'Charcoal / L', 'L', 4, 'Charcoal', '#363636', 799900, 999900, 10, null, 2),
  (md5('clothsy:variant:v_blazer_black')::uuid, md5('clothsy:product:p_lavender_blazer')::uuid, md5('clothsy:seller:sel_noor')::uuid, 'v_blazer_black', 'Midnight Black / XL', 'XL', 5, 'Midnight Black', '#1A1A1A', 799900, 999900, 10, null, 3),
  (md5('clothsy:variant:v_overshirt_sand')::uuid, md5('clothsy:product:p_minimal_overshirt')::uuid, md5('clothsy:seller:sel_rao')::uuid, 'v_overshirt_sand', 'Khaki Sand / M', 'M', 3, 'Khaki Sand', '#D2C4AE', 499900, null, 10, null, 0),
  (md5('clothsy:variant:v_overshirt_charcoal')::uuid, md5('clothsy:product:p_minimal_overshirt')::uuid, md5('clothsy:seller:sel_rao')::uuid, 'v_overshirt_charcoal', 'Deep Charcoal / L', 'L', 4, 'Deep Charcoal', '#2E2E2E', 499900, null, 10, null, 1),
  (md5('clothsy:variant:v_hoodie_lavender')::uuid, md5('clothsy:product:p_lavender_hoodie')::uuid, md5('clothsy:seller:sel_lilac')::uuid, 'v_hoodie_lavender', 'Pastel Lilac / M', 'M', 3, 'Pastel Lilac', '#B9A6E0', 399900, 499900, 10, null, 0),
  (md5('clothsy:variant:v_hoodie_white')::uuid, md5('clothsy:product:p_lavender_hoodie')::uuid, md5('clothsy:seller:sel_lilac')::uuid, 'v_hoodie_white', 'Cloud White / S', 'S', 2, 'Cloud White', '#F5F5F7', 399900, 499900, 10, null, 1),
  (md5('clothsy:variant:v1_plum')::uuid, md5('clothsy:product:p1')::uuid, md5('clothsy:seller:sel_noor')::uuid, 'v1_plum', 'Plum Noir / M', 'M', 3, 'Plum Noir', '#2B1E3F', 499900, 799900, 10, 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=900&auto=format&fit=crop&q=80', 0),
  (md5('clothsy:variant:v1_lilac')::uuid, md5('clothsy:product:p1')::uuid, md5('clothsy:seller:sel_noor')::uuid, 'v1_lilac', 'Soft Lilac / S', 'S', 2, 'Soft Lilac', '#B9A6E0', 499900, 799900, 10, 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=900&auto=format&fit=crop&q=80', 1),
  (md5('clothsy:variant:v1_cream')::uuid, md5('clothsy:product:p1')::uuid, md5('clothsy:seller:sel_noor')::uuid, 'v1_cream', 'Champagne / L', 'L', 4, 'Champagne', '#FAF7F3', 499900, 799900, 10, null, 2),
  (md5('clothsy:variant:v2_sand')::uuid, md5('clothsy:product:p2')::uuid, md5('clothsy:seller:sel_rao')::uuid, 'v2_sand', 'Warm Sand / M', 'M', 3, 'Warm Sand', '#D9CCA8', 649900, 899900, 10, null, 0),
  (md5('clothsy:variant:v2_sage')::uuid, md5('clothsy:product:p2')::uuid, md5('clothsy:seller:sel_rao')::uuid, 'v2_sage', 'Sage Olive / L', 'L', 4, 'Sage Olive', '#2E7D5B', 649900, 899900, 10, null, 1),
  (md5('clothsy:variant:v3_lilac')::uuid, md5('clothsy:product:p3')::uuid, md5('clothsy:seller:sel_lilac')::uuid, 'v3_lilac', 'Lilac Dusk / S', 'S', 2, 'Lilac Dusk', '#B9A6E0', 529900, 699900, 10, null, 0),
  (md5('clothsy:variant:v4_ivory')::uuid, md5('clothsy:product:p4')::uuid, md5('clothsy:seller:sel_mehr')::uuid, 'v4_ivory', 'Ivory / M', 'M', 3, 'Ivory Cream', '#FAF7F3', 349900, 499900, 10, null, 0),
  (md5('clothsy:variant:v5_black')::uuid, md5('clothsy:product:p5')::uuid, md5('clothsy:seller:sel_noor')::uuid, 'v5_black', 'Obsidian Black / One Size', 'One Size', 7, 'Obsidian Black', '#1A1523', 849900, 1199900, 10, null, 0),
  (md5('clothsy:variant:v6_nude')::uuid, md5('clothsy:product:p6')::uuid, md5('clothsy:seller:sel_rao')::uuid, 'v6_nude', 'Champagne / 38', '38', 100, 'Champagne', '#E7DFF6', 549900, 749900, 10, null, 0)
;

insert into public.tryon_presets (id, slug, label, image_url, sort_order) values
  (md5('clothsy:preset:preset_model_1')::uuid, 'preset_model_1', 'Elena (Studio Neutral)', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb', 0),
  (md5('clothsy:preset:preset_model_2')::uuid, 'preset_model_2', 'Sora (Editorial Minimal)', 'https://images.unsplash.com/photo-1517841905240-472988babdf9', 1),
  (md5('clothsy:preset:preset_model_3')::uuid, 'preset_model_3', 'Zara (Daylight Chic)', 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1', 2),
  (md5('clothsy:preset:preset_model_4')::uuid, 'preset_model_4', 'Marcus (Tailored Fit)', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d', 3)
;
